skalla/api/urls.py
from rest_framework import routers
from cliente.views import ClienteViewSet, PerfilJornadaViewSet, PontoAlocacaoViewSet, TurnoPontoAlocacaoViewSet, EscalaViewSet, EscalaColaboradorViewSet
from empresa.views import ColaboradorViewSet

class RotasApi():
    rotasApi = routers.DefaultRouter()
    rotasApi.register('colaborador', ColaboradorViewSet, 'Colaborador')
    rotasApi.register('escala', EscalaViewSet, 'Escala')
    rotasApi.register('escala-colaborador', EscalaColaboradorViewSet, 'EscalaColaborador')


    rotasApi.register('cliente', ClienteViewSet, 'Cliente')
    rotasApi.register('perfil-jornada', PerfilJornadaViewSet, 'PerfilJornada')
    rotasApi.register('ponto-alocacao', PontoAlocacaoViewSet, 'PontoAlocacao')
    rotasApi.register('turno-ponto', TurnoPontoAlocacaoViewSet, 'TurnoPontoAlocacao')

skalla/skalla/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers
from api.urls import RotasApi
from django.conf import settings
from django.conf.urls.static import static

# from core import views
from web import views as webview

urlpatterns = [
    path('', webview.index),
    path('criaescala/', webview.criaEscala),
    path('minhaescala/', webview.minhaEscala),
    path('imprimirminhaescala/', webview.imprimirMinhaEscala),
    path('gestaoescalas/', webview.gestaoEscala),
    path('solicitacoes/', webview.solicitacoes),
    path('escalas/', webview.escalas),
    path('imprimirescalas/', webview.imprimirEscalas),
    path('imprimirescala/', webview.imprimirEscala),
    path('api/', include(RotasApi.rotasApi.urls)),
    path('admin/', admin.site.urls),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

skalla/cliente/models.py
from django.db import models
from django.core.validators import MinValueValidator
from core.models import Cidade
from empresa.models import Colaborador

# STATUS = (
#     (0, 'AGENDADO'),
#     (1, 'CONFIRMADO'),
#     (2, 'REJEITADO'),
#     (3, 'CANCELADO')
# )

# Create your models here.
class Cliente(models.Model):
    id = models.AutoField(primary_key=True)
    nome = models.CharField(max_length=150, verbose_name="Razão Social")
    nomeFantasia = models.CharField(max_length=150, verbose_name="Nome Fantasia")
    CNPJ = models.CharField(max_length=20, unique=True, verbose_name="CNPJ")
    IE = models.CharField(max_length=30, unique=True, verbose_name="Inscrição Estadual")
    IM = models.CharField(max_length=30, unique=True, verbose_name="Inscrição Municipal", null=True)
    logo = models.ImageField(upload_to='logo', blank=True, verbose_name="Logotipo")
    # endereco = models.ForeignKey(Endereco, related_name="endereco_cliente", on_delete=models.PROTECT, verbose_name="Endereço")
    telefone = models.CharField(max_length=20, unique=True, verbose_name="Telefone")
    contatoEscala = models.CharField(max_length=50, unique=True, verbose_name="Contato para escalas")
    contatoEscalaFone = models.CharField(max_length=20, unique=True, verbose_name="Telefone contato para escalas")
    FinanceiroContato = models.CharField(max_length=50, unique=True, verbose_name="Contato financeiro")
    FinanceiroEmail = models.CharField(max_length=255, unique=True, verbose_name="Email financeiro")

    cep = models.CharField(max_length=10)
    logradouro = models.CharField(max_length=50)
    numero = models.CharField(max_length=6)
    bairro = models.CharField(max_length=50)
    complemento = models.CharField(max_length=100, null=True, blank=True)
    referencia = models.CharField(max_length=100, null=True, blank=True)
    cidade = models.ForeignKey(Cidade, on_delete=models.PROTECT, related_name='cliente_cidade')

    def __str__(self):
        return self.nomeFantasia

    class Meta:
        verbose_name = "Cliente"
        verbose_name_plural = "Clientes"
        ordering = ['nomeFantasia']


class PontoAlocacao(models.Model):
    id = models.AutoField(primary_key=True)
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE, verbose_name="Cliente", related_name='cliente_ponto')
    nome = models.CharField(max_length=50, verbose_name="Ponto de Alocação")
    descricao = models.TextField( verbose_name="Descrição do Local")
    # endereco = models.ForeignKey(Endereco, on_delete=models.PROTECT, verbose_name="Endereço")

    cep = models.CharField(max_length=10)
    logradouro = models.CharField(max_length=50)
    numero = models.CharField(max_length=6)
    bairro = models.CharField(max_length=50)
    complemento = models.CharField(max_length=100, null=True, blank=True)
    referencia = models.CharField(max_length=100, null=True, blank=True)
    cidade = models.ForeignKey(Cidade, on_delete=models.PROTECT, related_name='ponto_cidade')

    class Meta:
        verbose_name = "Ponto de Alocação"
        verbose_name_plural = "Pontos de Alocação"
        ordering = ['cliente','nome']
    def __str__(self):
        return self.cliente.nomeFantasia + ' - ' + self.nome


class Turno(models.Model):
    id = models.AutoField(primary_key=True)
    descricao = models.CharField(max_length=50, verbose_name="Turno")
    periodo = models.CharField(max_length=50, verbose_name="Período")
    horasTrabalhadas = models.PositiveSmallIntegerField(validators=[MinValueValidator(0)], verbose_name="Qtde de horas de trabalho")
    horasDescanso = models.PositiveSmallIntegerField(validators=[MinValueValidator(0)], verbose_name="Qtde de horas de descanso")
    horaInicio = models.TimeField(verbose_name="Hora início do turno")
    horaFim = models.TimeField(verbose_name="Hora final do turno")
    ativo = models.BooleanField(default=True)

    class Meta:
        verbose_name = "Turno"
        verbose_name_plural = "Turnos de trabalho"
        ordering = ['descricao']

    def __str__(self):
        return self.descricao


class Turno_PontoAlocacao(models.Model):

    id = models.AutoField(primary_key=True)
    turno = models.ForeignKey(Turno, on_delete=models.PROTECT, related_name="turno_ponto", verbose_name="Turno")
    pontoAlocacao = models.ForeignKey(PontoAlocacao, on_delete=models.PROTECT, related_name="ponto_turno", verbose_name="Ponto de Alocação")
    qtdeColaboradores = models.PositiveSmallIntegerField(validators=[MinValueValidator(1)],verbose_name="Quantidade de colaboradores")


    def __str__(self):
        return self.id.__str__() + ' - ' + self.turno.id.__str__() + ' / ' + self.pontoAlocacao.id.__str__()

    class Meta:
        verbose_name = "Turno / Ponto de Alocação"
        verbose_name_plural = "Turno / Ponto de Alocação"
        unique_together = ['turno','pontoAlocacao']


class PerfilJornada(models.Model):
    id = models.AutoField(primary_key=True)
    descricao = models.CharField(max_length=50, verbose_name="Descrição")
    tipo = models.CharField(max_length=50, verbose_name="Tipo")
    dias = models.PositiveSmallIntegerField(validators=[MinValueValidator(1)],default=1)
    duplicar = models.BooleanField(default=False)
    horasAntecedenciaDuplicacao = models.PositiveSmallIntegerField(validators=[MinValueValidator(0)], verbose_name="Horas de antecedencia para duplicar")

    def __str__(self):
        return self.descricao

    class Meta:
        verbose_name = "Perfil de Jornada"
        verbose_name_plural = "Perfis de Jornada"


class Escala(models.Model):
    id = models.AutoField(primary_key=True)
    perfil = models.ForeignKey(PerfilJornada, on_delete=models.PROTECT,related_name='perfil_escala', verbose_name="Perfil de Jornada")
    turnoPonto = models.ForeignKey(Turno_PontoAlocacao, on_delete=models.PROTECT,related_name='turnoponto_escala', verbose_name="Turno / Ponto de alocação")
    dataInicio = models.DateTimeField()
    dataFim = models.DateTimeField()
    dataDuplicacao = models.DateTimeField()
    dataCancelamento = models.DateTimeField(null=True, blank=True)
    status = models.PositiveSmallIntegerField( default=0)     # 0 - Ativa / 1 Cancelada

    def __str__(self):
        return self.perfil.descricao + ' / ' + self.dataInicio.strftime("%d %m %Y %H:%M")

    class Meta:
        verbose_name = "Escala"
        verbose_name_plural = "Escalas"

class EscalaColaborador(models.Model):
    id = models.AutoField(primary_key=True)
    escala = models.ForeignKey(Escala, on_delete=models.PROTECT, related_name="escala_colaborador", verbose_name="Escala")
    colaborador = models.ForeignKey(Colaborador, on_delete=models.PROTECT, related_name="colaborador_escala", verbose_name="Colaborador")
    dataInicio = models.DateTimeField()
    dataFim = models.DateTimeField()
    dataRegistro = models.DateTimeField(auto_now_add=True)
    dataConfirmacao = models.DateTimeField(null=True, blank=True)
    dataCancelamento = models.DateTimeField(null=True, blank=True)
    status = models.PositiveSmallIntegerField( default=0) # 0 - Agendado - 1 - Confirmado - 2 - Rejeitado - 3 - Cancelado
    dataSolicitacaoAlteracao = models.DateTimeField(null=True, blank=True)
    dataRetornoSolicitacaoAlteracao = models.DateTimeField(null=True, blank=True)
    solicitacaoAlteracao = models.CharField(max_length=255, blank=True, null=True)
    statusSolicitacao = models.SmallIntegerField(null=True, blank=True) # 1 - PENDENTE - 2 - Aceita - 3 - RECUSADA
    retornoSolicitacao = models.CharField(max_length=255, blank=True, null=True)

skalla/empresa/models.py
from django.db import models
from django.core.validators import MinValueValidator
from core.models import Cidade
from core.models import Configuracao
from django.contrib.auth.models import User, Group


# Create your models here.
class Empresa(models.Model):
    id = models.AutoField(primary_key=True)
    nome = models.CharField(max_length=150, verbose_name="Razão Social")
    nomeFantasia = models.CharField(max_length=150, verbose_name="Nome Fantasia")
    CNPJ = models.CharField(max_length=20, unique=True, verbose_name="CNPJ")
    IE = models.CharField(max_length=20, unique=True, verbose_name="Inscrição Estadual")
    logo = models.ImageField(upload_to='logo', blank=True, verbose_name="Logotipo")
    # endereco = models.ForeignKey(Endereco, related_name="endereco_empresa", on_delete=models.PROTECT, verbose_name="Endereço")
    dataAbertura = models.DateField(verbose_name="Data de Abertura")

    diasAntecedenciaSolicitacao = models.PositiveSmallIntegerField(default=0, verbose_name="Dias antecedencia", help_text="Dias de antecedência para solicitação de alteração")

    cep = models.CharField(max_length=10)
    logradouro = models.CharField(max_length=50)
    numero = models.CharField(max_length=6)
    bairro = models.CharField(max_length=50)
    complemento = models.CharField(max_length=100, null=True, blank=True)
    referencia = models.CharField(max_length=100, null=True, blank=True)
    cidade = models.ForeignKey(Cidade, on_delete=models.PROTECT, related_name='empresa_cidade')


    def __str__(self):
        return self.nomeFantasia

    class Meta:
        verbose_name = "Empresa"
        verbose_name_plural = "Empresas"
        ordering = ['nomeFantasia']


class Area(models.Model):
    id = models.AutoField(primary_key=True)
    nome = models.CharField(max_length=50, verbose_name="Área")
    responsavel = models.ForeignKey(User, on_delete=models.PROTECT,related_name="user_area", verbose_name="Usuário Responsável")

    class Meta:
        verbose_name = "Área"
        verbose_name_plural = "Áreas"
        ordering = ['nome']
    def __str__(self):
        return self.nome


class Departamento(models.Model):
    id = models.AutoField(primary_key=True)
    nome = models.CharField(max_length=50, verbose_name="Departamento")
    area = models.ForeignKey(Area, on_delete=models.CASCADE, related_name="area_departamento", verbose_name="Área")
    responsavel = models.ForeignKey(User, on_delete=models.PROTECT,related_name="user_departamento", verbose_name="Usuário Responsável")

    class Meta:
        verbose_name = "Departamento"
        verbose_name_plural = "Departamentos"
        ordering = ['area','nome']

    def __str__(self):
        return self.area.nome + ' - ' + self.nome

class Colaborador(User):
    empresa = models.ForeignKey(Empresa, on_delete=models.CASCADE, related_name="empresa_area", verbose_name="Empresa")
    dataNascimento = models.DateField(verbose_name="Data de Nascimento")
    telefone = models.CharField(max_length=20, verbose_name="Telefone")
    celular = models.CharField(max_length=20, verbose_name="Celular")
    contato = models.CharField(max_length=20, verbose_name="Contato")
    contatoFone = models.CharField(max_length=20, verbose_name="Telefone Contato")
    dataAdmissao = models.DateField(verbose_name="Data Admissão")
    PIS = models.CharField(max_length=20)
    departamento = models.ForeignKey(Departamento, on_delete=models.PROTECT, related_name='depto_colaborador', verbose_name='Departamento')
    limiteHorasMes = models.SmallIntegerField( validators=[MinValueValidator(1)], verbose_name="Máximo de horas de trabalho mensal")
    limiteHorasSemana = models.SmallIntegerField(validators=[MinValueValidator(1)], verbose_name="Máximo de horas de trabalho semanal")

    # periodosInativos = OneToMany(to=PeriodoInativo)

    def __str__(self):
        return self.first_name

    def nome(self):
        return self.first_name

    def sobrenome(self):
        return self.last_name

    def email(self):
        return self.email

    def save(self, *args, **kwargs):
        novo = False
        if self.id == None:
            novo = True
            self.is_staff = True;
            self.set_password('123456')

        super().save(*args, **kwargs)
        if novo:
            config = Configuracao.objects.first()
            config.grupoColaborador.user_set.add(self)

    class Meta:
        verbose_name = "Colaborador"
        verbose_name_plural = "Colaboradores"
        # ordering = ['usuario__name']


class PeriodoInativo(models.Model):
    id = models.AutoField(primary_key=True)
    descricao = models.CharField(max_length=100)
    colaborador = models.ForeignKey(Colaborador, on_delete=models.CASCADE, related_name="colaborador_periodo", verbose_name="Colaborador")
    dataRegistro = models.DateTimeField(auto_now_add=True)
    dataInicio = models.DateField(verbose_name="Data início")
    dataFim = models.DateField(verbose_name="Data Fim")
    usuarioRegistro = models.CharField(max_length=150, verbose_name="Registrado Por")

    def __str__(self):
        return self.descricao

    class Meta:
        verbose_name = "Período de Inatividade"
        verbose_name_plural = "Períodos de Inatividade"
        ordering = ['dataRegistro']

skalla/web/templates/criaescala.html
{% extends "layout/base_site.html" %}
{% load i18n admin_static %}

{% block extrastyle %}


  {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static 'web/styles/loader.css' %}" media="all">
{% endblock %}


{% block coltype %}colMS{% endblock %}

{% block bodyclass %}dashboard{% endblock %}

{% block breadcrumbs %}{% endblock %}
{% block content %}
<style>
    .negrito{
        font-weight: bold;
    }
    .warning-colaborador {
        color:red;
        background-color: #f0f0f0;
    }
</style>


<div id="content-main" class="container-fluid">
    <div class="tela-inteira" v-if="carregando">
         <div class="lds-hourglass"> </div>
    </div>

    <div style="white-space: pre;" class="alert alert-success" v-if="mensagemSucesso.length > 1">
        <button class="close" data-dismiss="alert">x</button>
        [[mensagemSucesso]]
    </div>
    <div style="white-space: pre;" class="alert alert-danger" v-if="mensagemErro.length > 1">
        <button class="close" data-dismiss="alert">x</button>
        [[mensagemErro]]
    </div>
    <div class="row">
        <form action="/escala/" method="post">
            {% csrf_token %}
            <ul style="list-style: none; float: left">
                <li style="float:left; padding: 5px">
                    <label for="perfil">Perfil:</label>
                    <select v-model="perfil" id="perfil" class="form-control">
                        <optgroup label="Selecione um Perfil"></optgroup>
                        <option v-for="p in perfis" v-bind:value="p">[[p.descricao]]</option>
                    </select>
                </li>
                <li style="float:left; padding: 5px">
                    <label for="dataInicio">Data de Início da Escala</label>
                    <input class="form-control" type="date" style="width:150px;" id="dataInicio" v-model="dataInicio" />
                </li>
                <li style="float:left; padding: 5px">
                    <label for="cliente">Cliente:</label>
                    <select v-model="cliente" id="cliente"  class="form-control">
                        <optgroup label="Selecione um Cliente"></optgroup>
                        <option v-for="c in clientes" v-bind:value="c">[[c.nomeFantasia]]</option>
                    </select>
                </li>
                <li style="float:left; padding: 5px">
                    <label for="ponto" v-if="cliente.id">Ponto de Alocação:</label>
                    <select v-model="ponto" v-if="cliente.id" id="ponto" class="form-control">
                        <optgroup label="Selecione um Ponto de Alocação"></optgroup>
                        <option v-for="p in pontos" v-bind:value="p">[[p.nome]] - [[p.descricao]]</option>
                    </select>
                </li>
                <li style="float:left; padding: 5px">
                    <label for="turno" v-if="ponto.id">Turnos do Ponto:</label>
                    <select v-model="turno" v-if="ponto.id" id="ponto" class="form-control">
                        <optgroup label="Selecione um Turno"></optgroup>
                        <option v-for="t in turnos" v-bind:value="t">[[t.turno.descricao]]</option>
                    </select>
                </li>
            </ul>

            <button type="button" class="btn btn-primary" v-on:click="salvaEscala()">Salvar Escala</button>
        </form>
    </div>
    <table class="table table-bordered" id="calendar" v-if="dataInicio && perfil.id">
      <thead>
        <tr>
          <th scope="col" v-for="d in perfil.dias">
              [[ dataInicio, (d - 1) | moment ]]
          </th>
        </tr>
      </thead>
      <tbody>
        <tr v-if="perfil.id && cliente.id && turno.id" style="font-size: 11px" >
          <td v-for="p in perfil.dias">
              <table class="table table-bordered">
                  <tr v-for="i in getIntervaloHoras(turno.turno.horaInicio, turno.turno.horaFim)">
                      <td>
                          <p >
                              [[ turno.turno.horaInicio, (i - 1) | horas ]]
                          </p>
                          <ul>
                              <li v-for="c in colaboradoresDia(p, (turno.turno.horaInicio, (i - 1)))">[[ c.colaborador.first_name ]] [[ c.colaborador.last_name ]]</li>
                          </ul>
                          <br/>
                            <a style="cursor: pointer;" v-on:click="abreModalColaboradores(
                                            dataInicio, p, (turno.turno.horaInicio), turno.turno, i)"
                                            data-toggle="modal" data-target="#modalColaboradores">Adicionar Colaborador</a>

                      </td>
                  </tr>
              </table>
          </td>
        </tr>

      </tbody>
    </table>
    <div class="modal fade" id="modalColaboradores" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Título do modal</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body" v-if="escalaColaborador.dataInicio && escalaColaborador.dataFim">
            Adicionar Colaborador em [[ escalaColaborador.dataInicio ]] até <br/> [[ escalaColaborador.dataFim ]]. <br/>
              <table style="width:100%;">
                  <thead>
                    <th>Colaborador</th>
                    <th>Ação</th>
                  </thead>
                  <tbody>
                    <tr v-for="c in retornaColaboradoresDisponiveisData(escalaColaborador.dataInicio)">
                        <td>
                            <strong>[[ c.first_name ]] [[ c.last_name ]]</strong>
                            <p class="warning-colaborador" v-if="c.horasDescanso < turno.turno.horasDescanso">CUIDADO! Esse colaborador está em período de descanso.</p>
                        </td>
                        <td>
                            <a v-on:click="adicionaColaboradorEscala(c)" style="text-underline: none;">Adicionar</a>
                        </td>
                    </tr>
                  </tbody>
              </table>
          </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                <button type="button" class="btn btn-primary">Salvar mudanças</button>
            </div>
        </div>
      </div>
    </div>

    <script type="application/javascript">
        var token = '{{csrf_token}}';
        var userId = "{{request.user.id}}";
    </script>

    <script src="{% static 'web/criaescala.js' %}"></script>
</div>

{% endblock %}

skalla/web/templates/imprimirescalas.html
{% extends "layout/base_site.html" %}
{% load i18n admin_static %}

{% block extrastyle %}


{{ block.super }}
<link rel="stylesheet" type="text/css" href="{% static 'web/styles/loader.css' %}" media="all">
{% endblock %}


{% block coltype %}colMS{% endblock %}

{% block bodyclass %}dashboard{% endblock %}

{% block breadcrumbs %}{% endblock %}
{% block content %}
<style>
  .negrito{
    font-weight: bold;
  }

  .escala-ativa{
    background-color:green !important;
  }

  .escala-inativa{
    background-color:gray !important;
  }

  .escala-cancelada{
    background-color:red !important;
  }

  .max-30{
    max-width: 30px;
  }
</style>


<div id="buscaescala">

  <div class="tela-inteira" v-if="carregando">
    <div class="lds-hourglass"> </div>
  </div>


  <div class="alert alert-success" v-if="mensagemSucesso.length > 1">
    <button class="close" data-dismiss="alert">x</button>
    [[mensagemSucesso]]
  </div>
  <div class="alert alert-danger" v-if="mensagemErro.length > 1">
    <button class="close" data-dismiss="alert">x</button>
    [[mensagemErro]]
  </div>
  <div class="toolbar-content clearfix">
    <div class="clearfix">
      <h3>Selecione as opções</h3>
      <div style="max-width: 100%">
        <table>
          <tr>
            <td>Tipo de Impressão</td>
            <td>
              <select name="tipo" v-model="tipoImpressao" data-placeholder="Selecione um Tipo de Impressão">
                <option value="empresa">Empresa</option>
                <option value="cliente">Cliente</option>
                <option value="ponto">Ponto de Alocação</option>
              </select>
            </td>
          </tr>
          <!-- <tr>
            <td>Mostrar canceladas</td>
            <td>
              <input class="form-control" type="checkbox" v-model="mostrarCanceladas">
            </td>
          </tr> -->

          <tr v-show="tipoImpressao === 'empresa' " ><td>Empresa</td><td><select style="height: 30px;" name="empresa"  @change="onChange()" id="id_empresa" data-placeholder="Selecione a empresa"></select></td></tr>
          <tr v-show="tipoImpressao === 'colaborador' "><td>Colaborador</td><td><select name="colaborador" v-model="filtroColaboradorId" id="id_colaborador" data-placeholder="Selecione um colaborador"></select></td></tr>
          <tr v-show="tipoImpressao === 'cliente' || tipoImpressao === 'ponto'" ><td>Cliente</td><td><select style="height: 30px;" name="cliente" v-model="filtroClienteId" id="id_cliente" data-placeholder="Selecione um Cliente"></select></td></tr>
          <tr v-show="tipoImpressao === 'ponto'"  ><td>Ponto Alocação</td><td><select style="height: 30px;" id="id_pontoalocacao" name="pontoAlocacao" v-model="filtroPontoAlocacaoId" data-placeholder="Selecione um Ponto de Alocação"></select></td></tr>
          <tr><td>Data Inicial</td><td><input style="height: 30px;" type="date" v-model="filtroDataInicial" placeholder="Data Inicial"></td></tr>
          <tr><td>Data Final</td><td><input style="height: 30px;" type="date" v-model="filtroDataFinal" placeholder="Data Final"></td> </tr>

          <tr>

            <td> <button type="button" :disabled="formInvalid()" v-on:click="imprimir()" class="btn btn-info btn-block">Imprimir</button></td>
          </tr>
          <tr></tr>
        </table>

      </div>
    </div>
  </div>
  <hr>
  <div v-if="mensagemSucesso" id="content" class="flex row-fluid">
    <div id="content-main">
      <div class="inner-center-column" style="width: 125%">
        <h1>[[mensagemSucesso]]</h1>



      </div>
    </div>
  </div>

  <!-- <div class="pagination-block">
    <div class="pagination">

      <ul class="pagination">

        <li v-bind:class="{ active: pagina == paginacao.page }" v-for="pagina in paginacao.paginas" v-on:click="buscar(pagina)" ><a href="javascript:void(0)"> [[pagina]] </a></li>

      </ul>
    </div>
  </div> -->

</div>


<script type="application/javascript">
  var token = '{{csrf_token}}';
  var userId = "{{request.user.id}}";
</script>
<script type="application/javascript" src="{% static 'web/imprimirescalas.js' %}"></script>

{% endblock %}

skalla/web/templates/index.html
{% extends "layout/base_site.html" %}
{% load i18n admin_static %}

{% block extrastyle %}


{{ block.super }}
<link rel="stylesheet" type="text/css" href="{% static 'web/styles/loader.css' %}" media="all">
{% endblock %}


{% block coltype %}colMS{% endblock %}

{% block bodyclass %}dashboard{% endblock %}

{% block breadcrumbs %}{% endblock %}
{% block content %}


{% endblock %}